/**
 * Centralized error codes for tg-cli.
 * Every outputError() call should reference these constants
 * instead of string literals to prevent typos and ease refactoring.
 */
export const ErrorCode = Object.freeze({
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  // Auth
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  NOT_INTERACTIVE: 'NOT_INTERACTIVE',

  // Input validation
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_OPTIONS: 'INVALID_OPTIONS',
  INVALID_TOPIC_ID: 'INVALID_TOPIC_ID',
  INVALID_MESSAGE_ID: 'INVALID_MESSAGE_ID',
  INVALID_MSG_ID: 'INVALID_MSG_ID',
  INVALID_MESSAGE_IDS: 'INVALID_MESSAGE_IDS',
  INVALID_REPLY_TO: 'INVALID_REPLY_TO',
  INVALID_COMMENT_TO: 'INVALID_COMMENT_TO',
  INVALID_INVITE: 'INVALID_INVITE',
  INVALID_CHAT_TYPE: 'INVALID_CHAT_TYPE',
  INVALID_ID: 'INVALID_ID',
  INVALID_FILTER: 'INVALID_FILTER',

  // Message
  MESSAGE_RESULT_UNAVAILABLE: 'MESSAGE_RESULT_UNAVAILABLE',
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  STDIN_REQUIRED: 'STDIN_REQUIRED',
  DELETE_MODE_REQUIRED: 'DELETE_MODE_REQUIRED',
  TOO_MANY_IDS: 'TOO_MANY_IDS',
  MISSING_QUERY: 'MISSING_QUERY',
  EMPTY_QUESTION: 'EMPTY_QUESTION',
  QUESTION_TOO_LONG: 'QUESTION_TOO_LONG',
  TOO_FEW_OPTIONS: 'TOO_FEW_OPTIONS',
  TOO_MANY_OPTIONS: 'TOO_MANY_OPTIONS',
  EMPTY_OPTION: 'EMPTY_OPTION',
  OPTION_TOO_LONG: 'OPTION_TOO_LONG',
  DUPLICATE_OPTION: 'DUPLICATE_OPTION',
  QUIZ_MISSING_CORRECT: 'QUIZ_MISSING_CORRECT',
  SOLUTION_WITHOUT_QUIZ: 'SOLUTION_WITHOUT_QUIZ',
  QUIZ_MULTIPLE_CONFLICT: 'QUIZ_MULTIPLE_CONFLICT',
  INVALID_CORRECT_INDEX: 'INVALID_CORRECT_INDEX',
  INVALID_CLOSE_IN: 'INVALID_CLOSE_IN',

  // Entity
  PEER_NOT_FOUND: 'PEER_NOT_FOUND',
  NOT_A_USER: 'NOT_A_USER',
  NOT_A_FORUM: 'NOT_A_FORUM',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  NO_USERS_FOUND: 'NO_USERS_FOUND',

  // Chat
  USER_ALREADY_PARTICIPANT: 'USER_ALREADY_PARTICIPANT',
  CHANNELS_TOO_MUCH: 'CHANNELS_TOO_MUCH',
  UNKNOWN_INVITE_TYPE: 'UNKNOWN_INVITE_TYPE',

  // Contact
  MISSING_FIRST_NAME: 'MISSING_FIRST_NAME',
  PHONE_NOT_FOUND: 'PHONE_NOT_FOUND',

  // Media
  ALBUM_TOO_LARGE: 'ALBUM_TOO_LARGE',
  NO_MEDIA: 'NO_MEDIA',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_EXISTS: 'FILE_EXISTS',

  // Session & client
  NO_SESSION: 'NO_SESSION',
  NO_INPUT: 'NO_INPUT',
  TIMEOUT: 'TIMEOUT',
  TOO_MANY_USERS: 'TOO_MANY_USERS',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  TG_ERROR: 'TG_ERROR',
  CREDENTIAL_ERROR: 'CREDENTIAL_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  SESSION_ERROR: 'SESSION_ERROR',
  INVALID_SESSION: 'INVALID_SESSION',
  VERIFY_FAILED: 'VERIFY_FAILED',
  FLOOD_WAIT: 'FLOOD_WAIT',

  // Presets
  FETCH_FAILED: 'FETCH_FAILED',
  UNKNOWN_PRESET: 'UNKNOWN_PRESET',

  // Daemon
  DAEMON_NOT_RUNNING: 'DAEMON_NOT_RUNNING',
  DAEMON_ALREADY_RUNNING: 'DAEMON_ALREADY_RUNNING',
  DAEMON_START_FAILED: 'DAEMON_START_FAILED',
  DAEMON_STOP_FAILED: 'DAEMON_STOP_FAILED',
  DAEMON_CONNECTION_FAILED: 'DAEMON_CONNECTION_FAILED',
  DAEMON_PROXY_UNAVAILABLE: 'DAEMON_PROXY_UNAVAILABLE',
  DAEMON_BUSY: 'DAEMON_BUSY',
  DAEMON_CANCELLED: 'DAEMON_CANCELLED',
  DAEMON_STOPPING: 'DAEMON_STOPPING',
  DAEMON_RESPONSE_TOO_LARGE: 'DAEMON_RESPONSE_TOO_LARGE',
} as const);

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
