/**
 * Centralized error codes for tg-cli.
 * Every outputError() call should reference these constants
 * instead of string literals to prevent typos and ease refactoring.
 */
export const ErrorCode = Object.freeze({
  // Auth
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  NOT_INTERACTIVE: 'NOT_INTERACTIVE',

  // Input validation
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_OPTIONS: 'INVALID_OPTIONS',
  INVALID_TOPIC_ID: 'INVALID_TOPIC_ID',
  INVALID_MESSAGE_ID: 'INVALID_MESSAGE_ID',
  INVALID_MSG_ID: 'INVALID_MSG_ID',
  INVALID_MESSAGE_IDS: 'INVALID_MESSAGE_IDS',
  INVALID_REPLY_TO: 'INVALID_REPLY_TO',
  INVALID_COMMENT_TO: 'INVALID_COMMENT_TO',
  INVALID_INVITE: 'INVALID_INVITE',
  INVALID_CHAT_TYPE: 'INVALID_CHAT_TYPE',
  INVALID_ID: 'INVALID_ID',

  // Message
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  STDIN_REQUIRED: 'STDIN_REQUIRED',
  DELETE_MODE_REQUIRED: 'DELETE_MODE_REQUIRED',

  // Entity
  PEER_NOT_FOUND: 'PEER_NOT_FOUND',
  NOT_A_USER: 'NOT_A_USER',
  NOT_A_FORUM: 'NOT_A_FORUM',
  NO_USERS_FOUND: 'NO_USERS_FOUND',

  // Chat
  USER_ALREADY_PARTICIPANT: 'USER_ALREADY_PARTICIPANT',
  CHANNELS_TOO_MUCH: 'CHANNELS_TOO_MUCH',
  UNKNOWN_INVITE_TYPE: 'UNKNOWN_INVITE_TYPE',

  // Contact
  MISSING_FIRST_NAME: 'MISSING_FIRST_NAME',
  PHONE_NOT_FOUND: 'PHONE_NOT_FOUND',

  // Media
  ALBUM_TOO_LARGE: 'ALBUM_TOO_LARGE',
  NO_MEDIA: 'NO_MEDIA',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',

  // Session & client
  NO_SESSION: 'NO_SESSION',
  TIMEOUT: 'TIMEOUT',
  TOO_MANY_USERS: 'TOO_MANY_USERS',

  // Daemon
  DAEMON_NOT_RUNNING: 'DAEMON_NOT_RUNNING',
  DAEMON_ALREADY_RUNNING: 'DAEMON_ALREADY_RUNNING',
  DAEMON_START_FAILED: 'DAEMON_START_FAILED',
  DAEMON_CONNECTION_FAILED: 'DAEMON_CONNECTION_FAILED',
} as const);

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
